### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [nicknist/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

Hey Nick! Good job on your assessment. You're really close to where we want you to be, and we appreciate that you reached out to us to figure out the issues you were having. That's the proactive nature that will help you succeed at Turing. I can tell you have a solid understanding of the core concepts of Mod-0. We do want you to have another go at git and file/directory-structure. We want you to create a new repository called `directory_and_git_skills` completely new and outside of either of the directories you created on the assessment. Then within that directory create all of the directories and files from this example from session-3: 
![directory-structure](https://user-images.githubusercontent.com/23040094/57975258-b3288f80-7982-11e9-9b78-ff1cfbf06920.png)

So `to_do` will be the first directory nested under the `directory_and_git_skills` and so forth. We want to see you making separate commits for certain files. Commit  the `random.txt` and `recurring.txt` together as one commit with a properly formatted commit message. Then commit the files within `home` together with a properly formatted commit message. Then commit everything within the `work` directory together with a properly formatted commit message.  Make sure to add a little random text to each file as Git may not be happy about committing empty files. I could also be making that up, but I know Git does not like empty directories. Send us a link to your repo when you're finished. Reach out if you have any questions. Thanks Nick!

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
